cloudera-labs/cloudera.cluster

galaxy.yml
Fix ansible-galaxy license statement
Signed-off-by: Daniel Chaffelson <chaffelson@gmail.com>
=> Fix ansible-galaxy license statement

plugins/filter/filters.py, roles/cloudera_manager/config/templates/cm_api.j2, roles/deployment/cluster/templates/cluster_template/base/hostTemplates.j2, roles/deployment/cluster/templates/cluster_template/base/instantiator.j2, roles/deployment/cluster/templates/cluster_template/base/services.j2, roles/deployment/cluster/templates/cluster_template/cm_api.j2, roles/deployment/cluster/templates/cluster_template/common/variables.j2, roles/verify/parcels_and_roles/tasks/check_cluster_config_roles.yml, roles/verify/parcels_and_roles/tasks/check_template_roles.yml
Adding the ability to specify custom role config groups by using the syntax ROLETYPE/CUSTOMROLENAME as follows:
```IMPALA:
IMPALAD:
scratch_dirs: /tmp/impala
IMPALAD/COORDINATOR:
impalad_specialization: COORDINATOR_ONLY
IMPALAD/EXECUTOR:
impalad_specialization: EXECUTOR_ONLY
```
Includes logic to fold in any default values from the config overlays (TLS, Kerberos, etc) and to inherit any base configs specified (for example `scratch_dirs` above).
Tested on a cluster with and without custom rcgs.
=> Add the ability to specify custom role config groups for sets of hosts

roles/config/cluster/base/templates/configs/kerberos-6.x-7.x.j2, roles/deployment/cluster/tasks/create_data_context.yml
Hi all, this PR makes the following changes:
Removes the CORE_SETTINGS configs that are auto-configured (must be unset for the cluster to successfully deploy).
Checks that HDFS is present before attempting to create a data context.
=> Changes required for Core Settings clusters

roles/deployment/groupby/tasks/main.yml, roles/verify/definition/tasks/main.yml, roles/verify/parcels_and_roles/tasks/check_template_roles.yml
This PR improves a number of error messages:
- Error when a host template does not exist (failed with a lookup failure before)
- Message explaining how to configure tls in the tls verify check
- Verify check to ensure that TEZ is included with each HIVESERVER2 HIVE_ON_TEZ role
=> Helpful errors

plugins/filter/filters.py, roles/config/cluster/base/templates/configs/kerberos-6.x-7.x.j2, roles/config/cluster/base/templates/configs/tls-cm-7.j2, roles/verify/parcels_and_roles/tasks/check_template_roles.yml
Plus some SMM template updates.
=> Fixed handling of custom roleConfig Groups

roles/infrastructure/ca_server/vars/RedHat.yml, roles/prereqs/os/tasks/main-RedHat.yml
Note that fixes in PR 81 on Cloudera Deploy makes deployments behave correctly on older versions of Ansible (2.10) when working with newer OS (el8), but are not required for this PR unless you are in fact testing that particular combination.
https://github.com/cloudera-labs/cloudera-deploy/pull/81
Change ca_server_root_key_cipher from aes256 to auto as a fix for more modern OS deployment standards
More robustly ensure python2/3 install and pip upgrade for el8
Fixes the very annoying mutiple versions of Python and where is cryptography hiding issues
Signed-off-by: Daniel Chaffelson <chaffelson@gmail.com>
=> Fix CA cipher and python2/3 install for newer OS targets like el8

.gitignore, meta/runtime.yml, plugins/doc_fragments/cm_endpoint.py, plugins/doc_fragments/cm_options.py, plugins/doc_fragments/cm_resource.py, plugins/module_utils/cm_utils.py, plugins/modules/cm_endpoint_info.py, plugins/modules/cm_resource.py, plugins/modules/cm_resource_info.py, plugins/modules/cm_version_info.py, pytest.ini, tests/config.yml, tests/unit/conftest.py, tests/unit/plugins/modules/cm_endpoint_info/test_cm_endpoint_info_i.py, tests/unit/plugins/modules/cm_resource/test_cm_resource_i.py, tests/unit/plugins/modules/cm_resource_info/test_cm_resource_info_i.py, tests/unit/plugins/modules/cm_version_info/test_cm_version_info_i.py, tests/unit/plugins/modules/utils.py, tests/unit/requirements.txt
Initial commit with a common `cm_utils.py` for managing CM API interactions, unit and integration test frameworks, and `cm_version_info` and `cm_endpoint_info` modules. Handles both direct URL and endpoint discovery.
Signed-off-by: Webster Mudge <wmudge@cloudera.com>
=> Cloudera Manager module framework

roles/cloudera_manager/admin_password/check/tasks/main.yml
If LDAP is configured in CM, repeated failed password checks can lock user accounts.
After LDAP has been configured or the CM admin password is changed, the CM password check will trigger a failed login each time it is used.
This commit adds checks to ensure the check is skipped each time it is run after the first failure.
This is okay as we don't expect the CM password to be changed back to its default value.
Signed-off-by: William Dyson <wdyson@cloudera.com>
=> Avoid repeating CM password check

roles/cloudera_manager/admin_password/check/tasks/main.yml, roles/cloudera_manager/api_hosts/tasks/main.yml, roles/cloudera_manager/config/tasks/main.yml, roles/security/tls_install_certs/tasks/main.yml
Updates to handle deployments into private, i.e. jump host enabled, installations in cloud providers like AWS EC2
=> Updates for private IP installations

roles/config/cluster/base/templates/configs/inter-service-dependencies.j2
Remove hive as a dependency : property hive_service does not exist
=> #65 Fix SPARK3_ON_YARN inter-service dependency

.github/workflows/validate_pr.yml, bindep.txt, galaxy.yml
Signed-off-by: Webster Mudge <wmudge@cloudera.com>
=> Remove bindep requirements for community.general.ipa_user

roles/deployment/databases/tasks/postgresql.yml, roles/infrastructure/krb5_client/tasks/freeipa.yml
This PR has two changes required to deploy PvC on IaaS with sidecar FreeIPA (which is installed as part of the pre_setup).
1. Added a guard condition to prevent the FreeIPA client being installed when the `krb5_server` Ansible host group is not defined.
2. Revert the change in #112 which installs the psycopg2 during the db configuration. This fails when the task file is not executed as root user. Configuring of external dependency packages should be done as part of external dependencies - e.g. `cloudera.cluster.infrastructure.rdbms`
=> Fixes for PvC running on PvC with sidecar FreeIPA

docs/freeipa.md, roles/infrastructure/krb5_client/defaults/main.yml, roles/infrastructure/krb5_client/tasks/freeipa.yml
Allow you to suppress client enrollment with an existing FreeIPA server - current operation assumes either enrollment prior to automation or that you are installing the FreeIPA server alongside the client during the automation.
=> Add 'freeipa_enroll' optional parameter 

plugins/lookup/cm_service.py, plugins/module_utils/cm_controller_utils.py, plugins/module_utils/cm_utils.py, plugins/modules/cm_resource.py
Move code into new 'cm_controller_utils.py' file and update imports.
Closes #135
=> Move non-controller code in 'module_utils/cm_utils' 

roles/config/cluster/base/templates/configs/inter-service-dependencies.j2
Fixes Issue #122
In CDP using spark_on_yarn is not supported anymore (replaced by hive on tez)
=> use spark_on_yarn_service dependency for hive in CDH only

roles/config/cluster/base/templates/configs/databases-7.1.9.j2, roles/config/cluster/base/vars/main.yml, roles/deployment/definition/defaults/main.yml
In 7.1.9 QueueManager uses RDBMS. postgresql only supported in 7.1.9.0 & CHF1, Switch to back to legacy H2 included in CHF2, other db's later
=> Adds 7.1.9 QueueManager for postgresql

roles/config/cluster/base/vars/main.yml
There's an extra quotation mark in the condition for the configs/databases-7.1.0.j2 custom configuration template variable. This PR fixes that issue.
=> Remove extra quote from databases-7.1.0 config condition

roles/deployment/cluster/tasks/main.yml
Allows finer grain control on exactly which type cluster to deploy from a cluster.yml file, the default legacy behavior remains (it creates all clusters found in a cluster.yml file). Can provide a "-e to_deploy=<value>" in command line current values: base
encryption  (a kts cluster)
compute
ecs
Thanks npopa@cloudera.com
Signed-off-by: Chuck Levesque <clevesque@cloudera.com>
=> Allow selection of cluster deployed from cluster.yml

roles/config/cluster/base/templates/configs/databases-7.1.9.j2, roles/config/cluster/base/vars/main.yml, roles/deployment/definition/defaults/main.yml
Fix typo on svc name - Adds 7.1.9 QueueManager for postgresql
In 7.1.9 QueueManager uses RDBMS. postgresql only supported in 7.1.9.0 & CHF1, Switch to back to legacy H2 included in CHF2, other db's later
Signed-off-by: Chuck Levesque <clevesque@cloudera.com>
=> Fix typo - Feature qmanagerdb

plugins/action/assemble_cluster_template.py, plugins/modules/assemble_cluster_template.py
A module/action pair for building a single, composite Cloudera Manager cluster template from a set of cluster template "fragments." The plugins handle the merger of the JSON configuration files much like `ansible.builtin.assemble` but honor elements of the cluster template schema.
=> Create module and action plugins for assemble_cluster_template

roles/cloudera_manager/external_auth/templates/external_auth_configs.j2
Add option for complex LDAP search filters. Older implementation assumed all ldap filters end with "={0}". This newer implementation allows the user to craft any legal filter expression, including complex compound expressions, like ((&(member={0})(objectclass=posixgroup)(!(cn=admin))). This example would handle the IPA group search filter for ECS 1.5.x
=> Allow complex expressions in external authentication LDAP search filters

roles/cloudera_manager/license/tasks/enterprise.yml, roles/cloudera_manager/repo/tasks/main-RedHat.yml
=> Remove deprecated "warn" argument from shell and command module calls

roles/deployment/credential/tasks/main.yml, roles/prereqs/jdk/tasks/main.yml, roles/prereqs/license/tasks/main.yml, roles/prereqs/mysql_connector/tasks/main.yml, roles/prereqs/postgresql_connector/tasks/main.yml
Allows copying license file and extracting user/password to run during check/diff mode.
Allows "Capture installed Java provider" & "Capture installed Java version" tasks to run during check/diff mode, so that facts are populated successfully later
Allows Postgres or MySQL Connectors to run during check/diff mode
Signed-off-by: Chuck Levesque <clevesque@cloudera.com>
=> Removes blockers to running check mode & diff mode

plugins/modules/parcel.py, plugins/modules/parcel_info.py, tests/unit/plugins/modules/parcel/test_parcel.py, tests/unit/plugins/modules/parcel_info/test_parcel_info.py
Parcel Module:
- Facilitates the management of parcels on a Cluster by downloading, distributing, and activating them according to the specified state.
- Supported states include 'download', 'distribute', and 'activate', each corresponding to specific actions performed on parcels.
=> Add Parcel Module

docsbuild/build.sh, plugins/modules/cm_config.py, plugins/modules/cm_license.py, plugins/modules/cm_license_info.py, plugins/modules/cm_trial_license.py, plugins/modules/host.py, plugins/modules/parcel.py, plugins/modules/parcel_info.py, plugins/modules/service.py, plugins/modules/service_config.py, plugins/modules/service_role.py, plugins/modules/service_role_config.py, plugins/modules/service_role_config_group.py, plugins/modules/service_role_config_group_config.py
Clean up documentation build errors
=> Add or update API to support diff documentation

plugins/modules/host_config.py, plugins/modules/host_config_info.py, tests/unit/plugins/modules/host_config/test_host_config.py, tests/unit/plugins/modules/host_config_info/test_host_config_info.py
Pull Request:  Host Config Module + Host Config Info Module
=> Add Host Config Module

plugins/module_utils/data_context_utils.py, plugins/modules/data_context.py, plugins/modules/data_context_info.py, tests/unit/plugins/modules/data_contex/test_data_contex.py, tests/unit/plugins/modules/data_contex_info/test_data_context_info.py
This PR contains:
* Data Context Module
* Data Context Info Module
* Data Context utils
=> Data Context Module

plugins/module_utils/host_template_utils.py, plugins/modules/host_template.py, plugins/modules/host_template_info.py, tests/unit/plugins/modules/host_template/test_host_template.py, tests/unit/plugins/modules/host_template_info/test_host_template_info.py
This commit contains:
* Host Template Module
* Host Template Info Module
=> Add Host Template Module

plugins/modules/external_user_mappings.py, plugins/modules/external_user_mappings_info.py, tests/unit/plugins/modules/external_user_mappings/test_external_user_mappings.py, tests/unit/plugins/modules/external_user_mappings_info/test_external_user_mappings_info.py
This PR Contains:
* External_user_mappings Module
* External_user_mappings_info Module
=> Add External_user_mappings module

plugins/modules/cluster.py, tests/unit/plugins/modules/cluster/test_experience_cluster.py
This module enables deploying ECS on Private Cloud with cluster module.
Module can execute all steps like [create_ecs.yml](https://github.com/cloudera-labs/cloudera.cluster/blob/main/roles/deployment/cluster/tasks/create_ecs.yml)
Tested with CDH 7.1.9, CM 7.11.3.9 and  ECS 1.5.4.
=> Add ECS Control plane cluster functionality

plugins/module_utils/cm_utils.py, plugins/modules/cm_endpoint_info.py
Needs to return an error if unable to execute `GET /api/version`
=> Update cm_utils discover_endpoint function

plugins/module_utils/cm_utils.py
I believe the only plugin impacted by this is https://github.com/cloudera-labs/cloudera.cluster/blob/devel/plugins/modules/cluster.py#L1017-L1020. It should work as is because it already correctly uses objects which exist in the tuple return.
=> Add return value to wait_for_command_state

plugins/modules/cm_service_role_config_group.py, plugins/modules/service_role_config_group.py, plugins/modules/service_role_config_group_info.py, tests/unit/__init__.py, tests/unit/conftest.py, tests/unit/plugins/modules/cm_service_role_config_group/test_cm_service_role_config_group.py, tests/unit/plugins/modules/service_role_config_group/test_service_role_config_group.py, tests/unit/plugins/modules/service_role_config_group_info/test_service_role_config_group_info.py
Notably, this module no longer handles the role _association_ with the role config group. That responsibility will be delegated to other modules addressing `service` and `role` (including `cluster`).  This role does _report_ on role associations.
=> Update service_role_config_group to align with CM modules

plugins/module_utils/cluster_utils.py, plugins/module_utils/cm_utils.py, plugins/module_utils/host_template_utils.py, plugins/module_utils/host_utils.py, plugins/module_utils/parcel_utils.py, plugins/module_utils/role_utils.py, plugins/modules/cluster.py, plugins/modules/host.py, plugins/modules/host_info.py, plugins/modules/service.py, plugins/modules/service_info.py, tests/unit/plugins/modules/host/conftest.py, tests/unit/plugins/modules/host/test_host.py, tests/unit/plugins/modules/host/test_host_clusters.py, tests/unit/plugins/modules/host/test_host_host_templates.py, tests/unit/plugins/modules/host/test_host_rcgs.py, tests/unit/plugins/modules/host/test_host_role_configs.py, tests/unit/plugins/modules/host_info/test_host_info.py, tests/unit/plugins/modules/service_info/test_service_info.py
Role assignments via bidirectional host template and direct role config group assignment and per-role configuration overrides.
=> Update host and host_info modules for cluster membership and role assignments 

plugins/modules/cluster.py
Due to collision with existing TLS verification parameters
=> Change 'tls' parameter to 'auto_tls' 

plugins/modules/external_user_mappings.py
When creating new external_user_mappings, I get this error: `UnboundLocalError: local variable 'mapping' referenced before assignment`. I think I've traced this back to the simple change in this PR. I've tests the unit tests for external user mappings with this change and all run successfully.
=> Fix external_user_mapping module

README.md, plugins/modules/cm_autotls_info.py, plugins/modules/cm_kerberos_info.py, plugins/modules/cm_service_info.py, plugins/modules/cm_service_role_config_group_info.py, plugins/modules/cm_service_role_info.py, plugins/modules/external_account_info.py, plugins/modules/role_config_group_info.py
Also clean up some remaining documentation errors during API build
=> Update README for 5.0.0
